<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '$url is not valid' => '$url no es válida',
    'Abstract' => 'Resumen',
    'Add' => 'Agregar',
    'Are you sure you want to delete this item?' => '¿Estás seguro que deseas eliminar este elemento?',
    'Body' => 'Cuerpo',
    'Choose the type below' => 'Seleccione el tipo abajo',
    'Content "{page}" not found' => 'El contenido "{page}" no se encuentra',
    'Create new menu item for "{menu}"' => 'Crear nuevo elemento para "{menu}"',
    'Created At' => 'Creado',
    'Created By' => 'Creado por',
    'Delete' => 'Eliminar',
    'Draft' => 'Borrador',
    'File not found' => 'Archivo no encontrado',
    'Filename' => 'Nombre de archivo',
    'Gallery' => 'Galería',
    'ID' => '',
    'Image' => 'Imagen',
    'Images in gallery' => 'Imágenes en la Galería',
    'Label' => 'Etiqueta',
    'Language' => 'Idioma',
    'Media' => 'Adjunto',
    'Menu ID' => 'ID de Menú',
    'Menu not found' => 'Menú no encontrado',
    'Menus' => 'Menús',
    'Metadata Definition ID' => 'ID de Definición de Metadata',
    'Metadata Definitions' => 'Definiciones de Metadatos',
    'Mime Type' => 'Tipo Mime',
    'Name' => 'Nombre',
    'New Item' => 'Nuevo Elemento',
    'New Page' => 'Nueva Página',
    'New...' => 'Nuevo...',
    'Page ID' => 'ID de Página',
    'Page Type' => 'Tipo de Página',
    'Page Type ID' => 'ID de Tipo de Página',
    'Page Type not found' => 'Tipo de Página no encontrado',
    'Page Types' => 'Tipos de Página',
    'Pages' => 'Páginas',
    'Params' => 'Parámetros',
    'Parent ID' => 'ID de Padre',
    'Preview' => 'Vista Previa',
    'Published' => 'Publicado',
    'Read more...' => 'Leer más...',
    'Reset' => 'Restaurar',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Select an image' => 'Seleccione una Imagen',
    'Select content' => 'Seleccione un contenido',
    'Set' => 'Establecer',
    'Settings' => 'Configuración',
    'Slug' => '',
    'Status' => 'Estado',
    'Subpages' => 'Subpáginas',
    'The requested page does not exist.' => 'La página solicitada no existe',
    'The token is invalid' => 'El token es inválido',
    'The token must be set' => 'Tiene que configurar un token',
    'Title' => 'Título',
    'Token' => '',
    'Type' => 'Tipo',
    'URL' => '',
    'Update' => 'Actualizar',
    'Update Media: mode' => '',
    'Update Menu: mode' => '',
    'Update Metadata Definition: mode' => '',
    'Update Page Type: mode' => '',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Updated' => 'Actualizado',
    'Updated At' => 'Actualizado',
    'Updated By' => 'Actualizado por',
    'Website ID' => 'ID de Sitio Web',
    'Websites' => 'Sitios Web',
    'You can\'t delete one of the default page types.' => 'No puedes eliminar uno de los tipos de página por defecto',
    'You must save this page before adding subpages' => 'Debes guardar esta página antes de agregar subpáginas',
    '[Delete]' => '[Elmiminar]',
];
